"jobs":
  "check":
    "uses": "grafana/loki-release/.github/workflows/check.yml@d38f71c2aebadba3b097061b11d7cdce081785cd"
    "with":
      "build_image": "grafana/loki-build-image:0.34.5"
      "golang_ci_lint_version": "v1.60.3"
      "release_lib_ref": "d38f71c2aebadba3b097061b11d7cdce081785cd"
      "skip_validation": false
      "use_github_app_token": true
"name": "check"
"on":
  "pull_request": {}
  "push":
    "branches":
    - "main"