"jobs":
  "check":
    "uses": "grafana/loki-release/.github/workflows/check.yml@ff87b418529d99dc0fa9f757ff6253eb5695d833"
    "with":
      "build_image": "grafana/loki-build-image:0.34.5"
      "golang_ci_lint_version": "v1.60.3"
      "release_lib_ref": "ff87b418529d99dc0fa9f757ff6253eb5695d833"
      "skip_validation": false
      "use_github_app_token": true
"name": "check"
"on":
  "pull_request": {}
  "push":
    "branches":
    - "main"